version: "2"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - /Users/fnieto/Documents/Source/repos/testing/php-nginx:/code
      - /Users/fnieto/Documents/Source/repos/containerization/PHP-FPM_GINX/example.site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    image: php:7-fpm
    volumes:
      - /Users/fnieto/Documents/Source/repos/testing/php-nginx:/code
    networks:
      - code-network
networks:
    code-network:
      driver: bridge